export const COPY = {
  name: "ForeverFile",
  persistence:
    "Built to last far beyond ordinary hosting — not a promise against every future.",
  publicNotice: "Don't publish private or confidential files.",
  footer: "Public records on a long-lived network. This site is a window onto them.",
  hero: {
    overline: "Public files, unchanged.",
    title: "A permanent place for important files.",
    lead: "Publish a file. Keep it public, unchanged, and checkable.",
    primary: "Publish a file",
    secondary: "How it works",
  },
  properties: {
    intro: "What you get",
    public: {
      title: "Public",
      body: "Anyone with the record can view or download it.",
    },
    unchanged: {
      title: "Unchanged",
      body: "This version cannot silently become a different file.",
    },
    persistent: {
      title: "Persistent",
      body: "Built to outlast ordinary hosting and single accounts.",
    },
  },
  notThis: {
    title: "What this is not",
    items: [
      "Not private",
      "Not a backup",
      "Not reversible",
      "Not crypto",
    ],
  },
  closing: {
    title: "Publish once. Keep the record.",
    note: "You'll review the consequences before anything is written.",
  },
  publish: {
    chooseTitle: "Choose a file",
    chooseBody: "You'll confirm it's public and unchangeable before it is published.",
    dropLabel: "Drop a file here, or browse",
    dropHelper: "It will be public.",
    continue: "Continue",
    differentFile: "Choose another",
    reviewTitle: "Before you publish",
    publicTitle: "This file will be public.",
    publicBody: (name: string) =>
      `Anyone with the record can view or download ${name}.`,
    unchangedTitle: "This version cannot be changed.",
    unchangedBody:
      "No edit, overwrite, or silent swap. A later file becomes a new record.",
    privateTitle: "Not for private files.",
    privateBody: "If it shouldn't be public, stop here.",
    feeLabel: "Network fee",
    feeBody: "A one-time fee to the network that holds the file.",
    authorizeHint: "Next, you'll authorize in this browser. The key never leaves the tab.",
    ackPublic: "This file will be public",
    ackIrreversible:
      "This version cannot be changed, and deleting a link does not remove it",
    ackPrivate: "This is not private or confidential",
    publishCta: "Publish publicly",
    authorizeTitle: "Authorize",
    authorizeBody: "The key stays in this browser. ForeverFile never receives it.",
    authorizeHelper: "An Arweave key file, often named wallet.json.",
    chooseKey: "Choose key file",
    writing: "Writing the record…",
    emptyFile: "That file is empty.",
    largeFile:
      "Files must be 25 MiB or smaller for publishing.",
  },
  record: {
    kicker: "Record",
    unchangedExplainer:
      "Editing the copy on your computer does not change this record.",
    publicExplainer: "Anyone with this page can retrieve the file.",
    networkLabel: "Also on the network",
    networkBody: "Retrievable even if this website is gone.",
    download: "Download",
    copyLink: "Copy link",
    verify: "Verify",
    notFoundTitle: "No record found.",
    notFoundBody: "The link may be mistyped, or the record isn't on the network yet.",
    pendingTime: "Pending",
    publishedStatus: "Published and confirmed.",
    unchangedStatus: "Unchanged since publication.",
    pendingStatus: "Waiting for a publication time.",
  },
  verify: {
    title: "Verify a file",
    body: "Paste a link, or choose a local copy.",
    homeTitle: "Verify a file",
    homeBody: "Paste a link, or choose a local copy.",
    pasteLabel: "Link or record ID",
    pastePlaceholder: "foreverfile.xyz/f/…",
    chooseFile: "Choose file",
    cta: "Verify",
    verifying: "Checking…",
    verified: (date: string) => `Exactly the file published on ${date}.`,
    mismatch: "This copy does not match the published record.",
    notFound: "No public record for that link.",
    pending: "Record found. Publication time is still landing.",
    fileMissing: "Paste a link, or choose a local file.",
    tooLarge: "Byte verification supports files up to 25 MiB. You can still look up metadata without selecting a local file.",
    found: "Record found.",
    integrity: "The stored file doesn't match its published identity.",
    invalid: "That doesn't look like a ForeverFile link.",
  },
  how: {
    title: "How it works",
    lead: "You publish a specific file. The record stays public and checkable.",
    arweave:
      "Under the hood this is written to Arweave. You don't need Arweave tools to read a record.",
  },
} as const;
